# تم تقليص الذاكرة لـ 3 جيجا ليسهل حجزها على معالجات الـ ARM وتفادي الانهيار
org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# 👈 هذا السطر السحري يمنع كوتلن من محاولة فتح خادم منفصل قد ينهار في الخلفية
kotlin.compiler.execution.strategy=in-process

android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=true
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.19.10-hotspot